# Generated by Django 6.0 on 2025-12-23 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_appointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
