# Generated by Django 5.2.9 on 2026-01-08 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_alter_appointment_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='business_address',
            field=models.CharField(default='Default Business Location', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='business_name',
            field=models.CharField(default='Default Business Name', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
