# Generated by Django 6.0 on 2025-12-11 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_orderitem_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_amount',
        ),
    ]
