# Generated by Django 6.0 on 2025-12-18 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0002_alter_conversationmessage_options_conversation_cost_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='conversationmessage',
            name='seconds_from_start',
        ),
    ]
