# Generated by Django 6.0 on 2025-12-18 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0003_remove_conversation_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='duration_seconds',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
