# Generated by Django 6.0 on 2025-12-20 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0004_conversation_duration_seconds'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='duration_seconds',
        ),
    ]
