# Generated by Django 6.0 on 2025-12-20 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0005_remove_conversation_duration_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='duration_minutes',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='duration_ms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='duration_seconds',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
